import { fabric } from "fabric";

// Element templates source of truth
export const ELEMENT_TEMPLATES: { [key: string]: any } = {
  headshot: {
    label: "Headshot",
    type: "image-dropzone",
    x: 50,
    y: 50,
    size: 80,
    shape: "circle",
    visible: true,
    opacity: 1,
    zIndex: 1,
  },
  firstName: {
    label: "First Name",
    text: "Victoria",
    x: 150,
    y: 50,
    fontSize: 32,
    fontFamily: "Montserrat",
    color: "#000000",
    fontWeight: 700,
    visible: true,
    textAlign: "left",
    width: 300,
    zIndex: 2,
  },
  lastName: {
    label: "Last Name",
    text: "Bartholomew-Richardson",
    x: 150,
    y: 86,
    fontSize: 32,
    fontFamily: "Montserrat",
    color: "#000000",
    fontWeight: 700,
    visible: true,
    textAlign: "left",
    width: 300,
    zIndex: 2,
  },
  title: {
    label: "Title",
    text: "Vice President Marketing",
    x: 150,
    y: 90,
    fontSize: 20,
    fontFamily: "Montserrat",
    color: "#000000",
    fontWeight: 500,
    visible: true,
    textAlign: "left",
    width: 300,
    zIndex: 3,
  },
  company: {
    label: "Company",
    text: "Global Brands Inc.",
    x: 150,
    y: 120,
    fontSize: 20,
    fontFamily: "Montserrat",
    color: "#000000",
    fontWeight: 500,
    visible: true,
    textAlign: "left",
    width: 300,
    zIndex: 4,
  },
  companyLogo: {
    label: "Company Logo",
    type: "image-dropzone",
    x: 50,
    y: 150,
    size: 60,
    width: 148,
    height: 74,
    visible: true,
    opacity: 1,
    zIndex: 5,
  },
  eventLogo: {
    label: "Event Logo",
    type: "image-dropzone",
    x: 50,
    y: 50,
    size: 60,
    width: 220,
    height: 80,
    visible: true,
    opacity: 1,
    zIndex: 6,
  },
  gradientOverlay: {
    label: "Gradient Overlay",
    type: "gradient-overlay",
    x: 0,
    y: 300,
    width: 600,
    height: 300,
    gradientDirection: "bottom",
    overlayOpacity: 0.9,
    visible: true,
    zIndex: 3,
  },
  bg_gradient: {
    label: "Bottom Gradient (Overlay)",
    type: "rect",
    x: 0,
    y: 350,
    width: 600,
    height: 250,
    fill: "rgba(0,0,0,0.8)",
    visible: false,
    zIndex: 0,
  },
};
