import { fabric } from "fabric";

// Element templates source of truth
export const ELEMENT_TEMPLATES: { [key: string]: any } = {
  headshot: {
    label: "Headshot",
    type: "image-dropzone",
    x: 50,
    y: 50,
    size: 80,
    shape: "circle",
    visible: true,
    opacity: 1,
    zIndex: 1,
  },
  firstName: {
    label: "First Name",
    text: "First Name",
    x: 150,
    y: 50,
    fontSize: 32,
    fontFamily: "Montserrat",
    color: "#000000",
    fontWeight: 700,
    visible: true,
    textAlign: "left",
    width: 300,
    zIndex: 2,
  },
  lastName: {
    label: "Last Name",
    text: "Last Name",
    x: 150,
    y: 86,
    fontSize: 32,
    fontFamily: "Montserrat",
    color: "#000000",
    fontWeight: 700,
    visible: true,
    textAlign: "left",
    width: 300,
    zIndex: 2,
  },
  title: {
    label: "Title",
    text: "Title",
    x: 150,
    y: 90,
    fontSize: 20,
    fontFamily: "Montserrat",
    color: "#000000",
    fontWeight: 500,
    visible: true,
    textAlign: "left",
    width: 300,
    zIndex: 3,
  },
  company: {
    label: "Company",
    text: "Company",
    x: 150,
    y: 120,
    fontSize: 20,
    fontFamily: "Montserrat",
    color: "#000000",
    fontWeight: 500,
    visible: true,
    textAlign: "left",
    width: 300,
    zIndex: 4,
  },
  companyLogo: {
    label: "Company Logo | Colour",
    type: "image-dropzone",
    x: 50,
    y: 150,
    size: 60,
    width: 148,
    height: 74,
    visible: true,
    opacity: 1,
    zIndex: 5,
  },
  companyLogoWhite: {
    label: "Company Logo | White",
    type: "image-dropzone",
    x: 50,
    y: 240,
    size: 60,
    width: 148,
    height: 74,
    visible: true,
    opacity: 1,
    zIndex: 5,
  },
  eventLogo: {
    label: "Event Logo",
    type: "image-dropzone",
    x: 50,
    y: 50,
    size: 60,
    width: 220,
    height: 80,
    visible: true,
    opacity: 1,
    zIndex: 6,
  },
  bio: {
    label: "Bio",
    type: "dynamic-text",
    fieldId: "bio",
    text: "Bio",
    x: 150,
    y: 215,
    fontSize: 14,
    fontFamily: "Montserrat",
    color: "#000000",
    fontWeight: 400,
    visible: true,
    textAlign: "left",
    width: 300,
    zIndex: 7,
  },
  linkedin: {
    label: "LinkedIn",
    type: "icon-link",
    fieldId: "linkedin",
    iconType: "linkedin",
    x: 50,
    y: 245,
    size: 32,
    visible: true,
    zIndex: 8,
  },
  gradientOverlay: {
    label: "Gradient Overlay",
    type: "gradient-overlay",
    x: 0,
    y: 300,
    width: 600,
    height: 300,
    gradientDirection: "bottom",
    overlayOpacity: 0.9,
    visible: true,
    zIndex: 3,
  },
  bg_gradient: {
    label: "Bottom Gradient (Overlay)",
    type: "rect",
    x: 0,
    y: 350,
    width: 600,
    height: 250,
    fill: "rgba(0,0,0,0.8)",
    visible: false,
    zIndex: 0,
  },
};
