import { PresetData } from "@/types/card-builder";

// Website card templates exported as build functions that accept an `elementTemplates` object.
// The component wraps these with `makeApply` so the build can merge with local ELEMENT_TEMPLATES.

export const SQUARE_PRESETS_DATA: PresetData[] = [
  {
    name: "Overlay",
    description: "Full-bleed photo, gradient reveals text at the bottom",
    thumbnail: "overlay",
    thumbnailShape: "square",
    defaultBg: "#000000",
    defaultTextColor: "#ffffff",
    canvasW: 800,
    canvasH: 800,
    allowedHeadshotShapes: [],
    build: (T, bg = "#000000", textColor = "#ffffff", font = "Montserrat") => ({
      headshot:        { ...T.headshot, shape: "full-bleed", x: 0, y: 0, size: 800, zIndex: 1 },
      gradientOverlay: { ...T.gradientOverlay, x: 0, y: 420, width: 800, height: 380, gradientDirection: "bottom", overlayOpacity: 0.90, zIndex: 3 },
      companyLogo:     { ...T.companyLogo, x: 632, y: 20, width: 148, height: 74, size: 70, zIndex: 6 },
      name:            { ...T.name, x: 36, y: 528, color: textColor, fontFamily: font, fontSize: 55, nameFormat: "two-line", width: 728, fontWeight: 700, zIndex: 10 },
      title:           { ...T.title, x: 36, y: 651, color: textColor, fontFamily: font, fontSize: 28, width: 728, fontWeight: 500, zIndex: 8 },
      company:         { ...T.company, x: 36, y: 689, color: textColor, fontFamily: font, fontSize: 28, width: 500, fontWeight: 400, zIndex: 7 },
    }),
  },
  {
    name: "Headline",
    description: "Full-width name and details at top, circle photo below, logo bottom-left",
    thumbnail: "headline",
    thumbnailShape: "square",
    defaultBg: "#000000",
    defaultTextColor: "#ffffff",
    canvasW: 600,
    canvasH: 600,
    allowedHeadshotShapes: ["circle", "square", "rounded"],
    build: (T, bg = "#000000", textColor = "#ffffff", font = "Montserrat") => ({
      name:        { ...T.name, x: 24, y: 22, color: textColor, fontFamily: font, fontSize: 55, nameFormat: "two-line", width: 552, fontWeight: 700, zIndex: 4 },
      title:       { ...T.title, x: 24, y: 151, color: textColor, fontFamily: font, fontSize: 28, width: 552, fontWeight: 500, zIndex: 3 },
      company:     { ...T.company, x: 24, y: 189, color: textColor, fontFamily: font, fontSize: 28, width: 552, fontWeight: 400, zIndex: 2 },
      headshot:    { ...T.headshot, shape: "circle", x: 200, y: 265, size: 200, zIndex: 1 },
      companyLogo: { ...T.companyLogo, x: 20, y: 473, width: 148, height: 74, size: 70, zIndex: 5 },
    }),
  },
  {
    name: "Spotlight",
    description: "Centered circle photo, centered text below, clean and minimal",
    thumbnail: "spotlight",
    thumbnailShape: "square",
    defaultBg: "#000000",
    defaultTextColor: "#ffffff",
    canvasW: 600,
    canvasH: 600,
    allowedHeadshotShapes: ["circle", "square", "rounded"],
    build: (T, bg = "#000000", textColor = "#ffffff", font = "Montserrat") => ({
      companyLogo: { ...T.companyLogo, x: 204, y: 16, width: 192, height: 74, size: 70, zIndex: 6 },
      headshot:    { ...T.headshot, shape: "circle", x: 200, y: 100, size: 200, zIndex: 1 },
      name:        { ...T.name, x: 60, y: 321, color: textColor, fontFamily: font, fontSize: 55, nameFormat: "two-line", width: 480, textAlign: "center", fontWeight: 700, zIndex: 4 },
      title:       { ...T.title, x: 60, y: 450, color: textColor, fontFamily: font, fontSize: 28, width: 480, textAlign: "center", fontWeight: 500, zIndex: 3 },
      company:     { ...T.company, x: 60, y: 488, color: textColor, fontFamily: font, fontSize: 28, width: 480, textAlign: "center", fontWeight: 400, zIndex: 2 },
    }),
  },
];

export const LANDSCAPE_PRESETS_DATA: PresetData[] = [
  {
    name: "Overlay",
    description: "Full-bleed photo, gradient reveals text at the bottom",
    thumbnail: "overlay",
    thumbnailShape: "landscape",
    defaultBg: "#000000",
    defaultTextColor: "#ffffff",
    canvasW: 900,
    canvasH: 600,
    allowedHeadshotShapes: [],
    build: (T, bg = "#000000", textColor = "#ffffff", font = "Montserrat") => ({
      headshot:        { ...T.headshot, shape: "full-bleed", x: 0, y: 0, size: 900, zIndex: 1 },
      gradientOverlay: { ...T.gradientOverlay, x: 0, y: 271, width: 900, height: 329, gradientDirection: "bottom", overlayOpacity: 0.90, zIndex: 3 },
      companyLogo:     { ...T.companyLogo, x: 732, y: 18, width: 148, height: 74, size: 70, zIndex: 6 },
      name:            { ...T.name, x: 40, y: 321, color: textColor, fontFamily: font, fontSize: 55, nameFormat: "two-line", width: 560, fontWeight: 700, zIndex: 10 },
      title:           { ...T.title, x: 40, y: 450, color: textColor, fontFamily: font, fontSize: 28, width: 560, fontWeight: 500, zIndex: 8 },
      company:         { ...T.company, x: 40, y: 488, color: textColor, fontFamily: font, fontSize: 28, width: 380, fontWeight: 400, zIndex: 7 },
    }),
  },
  {
    name: "Side by Side",
    description: "Large square photo left, event logo and speaker info right",
    thumbnail: "side-by-side",
    thumbnailShape: "landscape",
    defaultBg: "#000000",
    defaultTextColor: "#ffffff",
    canvasW: 900,
    canvasH: 600,
    allowedHeadshotShapes: ["square", "rounded", "circle"],
    build: (T, bg = "#000000", textColor = "#ffffff", font = "Montserrat") => ({
      headshot:    { ...T.headshot, shape: "square", x: 36, y: 36, size: 480, zIndex: 1 },
      companyLogo: { ...T.companyLogo, x: 556, y: 36, width: 148, height: 74, size: 70, zIndex: 5 },
      name:        { ...T.name, x: 556, y: 130, color: textColor, fontFamily: font, fontSize: 55, nameFormat: "two-line", width: 308, fontWeight: 700, zIndex: 4 },
      title:       { ...T.title, x: 556, y: 259, color: textColor, fontFamily: font, fontSize: 22, width: 308, fontWeight: 500, zIndex: 3 },
      company:     { ...T.company, x: 556, y: 293, color: textColor, fontFamily: font, fontSize: 22, width: 308, fontWeight: 400, zIndex: 2 },
    }),
  },
  {
    name: "Editorial",
    description: "Full-bleed photo, bold headline lower panel — speaker name leads the card",
    thumbnail: "editorial",
    thumbnailShape: "landscape",
    defaultBg: "#000000",
    defaultTextColor: "#ffffff",
    canvasW: 900,
    canvasH: 600,
    allowedHeadshotShapes: [],
    build: (T, bg = "#000000", textColor = "#ffffff", font = "Montserrat") => ({
      headshot:        { ...T.headshot, shape: "full-bleed", x: 0, y: 0, size: 900, zIndex: 1 },
      gradientOverlay: { ...T.gradientOverlay, x: 0, y: 271, width: 900, height: 329, gradientDirection: "bottom", overlayOpacity: 0.95, zIndex: 3 },
      companyLogo:     { ...T.companyLogo, x: 728, y: 24, width: 148, height: 74, size: 70, zIndex: 6 },
      name:            { ...T.name, x: 40, y: 321, color: textColor, fontFamily: font, fontSize: 55, nameFormat: "two-line", width: 680, fontWeight: 800, zIndex: 10 },
      title:           { ...T.title, x: 40, y: 450, color: textColor, fontFamily: font, fontSize: 28, width: 580, fontWeight: 500, zIndex: 8 },
      company:         { ...T.company, x: 40, y: 488, color: textColor, fontFamily: font, fontSize: 28, width: 400, fontWeight: 400, zIndex: 7 },
    }),
  },
];

export const PORTRAIT_PRESETS_DATA: PresetData[] = [
  {
    name: "Overlay",
    description: "Full-bleed photo, gradient reveals text at the bottom",
    thumbnail: "overlay",
    thumbnailShape: "portrait",
    defaultBg: "#000000",
    defaultTextColor: "#ffffff",
    canvasW: 600,
    canvasH: 800,
    allowedHeadshotShapes: [],
    build: (T, bg = "#000000", textColor = "#ffffff", font = "Montserrat") => ({
      headshot:        { ...T.headshot, shape: "full-bleed", x: 0, y: 0, size: 600, zIndex: 1 },
      gradientOverlay: { ...T.gradientOverlay, x: 0, y: 401, width: 600, height: 399, gradientDirection: "bottom", overlayOpacity: 0.92, zIndex: 3 },
      companyLogo:     { ...T.companyLogo, x: 432, y: 20, width: 148, height: 74, size: 70, zIndex: 6 },
      name:            { ...T.name, x: 36, y: 521, color: textColor, fontFamily: font, fontSize: 55, nameFormat: "two-line", width: 528, fontWeight: 700, zIndex: 10 },
      title:           { ...T.title, x: 36, y: 650, color: textColor, fontFamily: font, fontSize: 28, width: 528, fontWeight: 500, zIndex: 8 },
      company:         { ...T.company, x: 36, y: 688, color: textColor, fontFamily: font, fontSize: 28, width: 380, fontWeight: 400, zIndex: 7 },
    }),
  },
  {
    name: "Spotlight",
    description: "Centered circle photo, centered text below — clean poster feel",
    thumbnail: "spotlight",
    thumbnailShape: "portrait",
    defaultBg: "#000000",
    defaultTextColor: "#ffffff",
    canvasW: 600,
    canvasH: 640,
    allowedHeadshotShapes: ["circle", "square", "rounded"],
    build: (T, bg = "#000000", textColor = "#ffffff", font = "Montserrat") => ({
      companyLogo: { ...T.companyLogo, x: 204, y: 16, width: 192, height: 74, size: 70, zIndex: 6 },
      headshot:    { ...T.headshot, shape: "circle", x: 180, y: 100, size: 240, zIndex: 1 },
      name:        { ...T.name, x: 60, y: 361, color: textColor, fontFamily: font, fontSize: 55, nameFormat: "two-line", width: 480, textAlign: "center", fontWeight: 700, zIndex: 4 },
      title:       { ...T.title, x: 60, y: 490, color: textColor, fontFamily: font, fontSize: 28, width: 480, textAlign: "center", fontWeight: 500, zIndex: 3 },
      company:     { ...T.company, x: 60, y: 528, color: textColor, fontFamily: font, fontSize: 28, width: 480, textAlign: "center", fontWeight: 400, zIndex: 2 },
    }),
  },
  {
    name: "Brand Forward",
    description: "Event logo dominates the top half, speaker photo and info fill the bottom",
    thumbnail: "brand-forward",
    thumbnailShape: "portrait",
    defaultBg: "#000000",
    defaultTextColor: "#ffffff",
    canvasW: 600,
    canvasH: 660,
    allowedHeadshotShapes: ["circle", "square", "rounded"],
    build: (T, bg = "#000000", textColor = "#ffffff", font = "Montserrat") => ({
      companyLogo: { ...T.companyLogo, x: 60, y: 28, width: 480, height: 160, size: 60, zIndex: 5 },
      headshot:    { ...T.headshot, shape: "circle", x: 220, y: 206, size: 160, zIndex: 1 },
      name:        { ...T.name, x: 60, y: 381, color: textColor, fontFamily: font, fontSize: 55, nameFormat: "two-line", width: 480, textAlign: "center", fontWeight: 700, zIndex: 4 },
      title:       { ...T.title, x: 60, y: 510, color: textColor, fontFamily: font, fontSize: 28, width: 480, textAlign: "center", fontWeight: 500, zIndex: 3 },
      company:     { ...T.company, x: 60, y: 548, color: textColor, fontFamily: font, fontSize: 28, width: 480, textAlign: "center", fontWeight: 400, zIndex: 2 },
    }),
  },
];

export const STARTER_PRESETS_DATA = [...SQUARE_PRESETS_DATA, ...LANDSCAPE_PRESETS_DATA, ...PORTRAIT_PRESETS_DATA];

export default {
  SQUARE_PRESETS_DATA,
  LANDSCAPE_PRESETS_DATA,
  PORTRAIT_PRESETS_DATA,
  STARTER_PRESETS_DATA,
};
